eventbrite-devise/config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get 'home/private'
  devise_for :users
  resources :events
  get '/events/:id(.:format)', to: 'events#destroy', as: 'destroy_event'
  resources :charges, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

eventbrite-devise/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

eventbrite-devise/app/models/event.rb
class Event < ApplicationRecord
    #belongs_to :user, class_name: 'User'
end

eventbrite-devise/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :events
end

eventbrite-devise/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

eventbrite-devise/app/controllers/charges_controller.rb
class ChargesController < ApplicationController
    def new
    end
    
    def create
      # Amount in cents
      @amount = 500
    
      customer = Stripe::Customer.create(
        :email => params[:stripeEmail],
        :source  => params[:stripeToken]
      )
    
      charge = Stripe::Charge.create(
        :customer    => customer.id,
        :amount      => @amount,
        :description => "Paiement effectué",
        :currency    => 'eur'
      )
    
    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path
    end
   
end

eventbrite-devise/app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    
    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Youpi, événement bien crée.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Yep, événement bien mis à jour !' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: ':( Ton événement est bien supprimé.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :description, :date, :location)
    end
end

eventbrite-devise/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def private
  end
  
  def devise
  end

end

eventbrite-devise/app/helpers/application_helper.rb
module ApplicationHelper
end

eventbrite-devise/app/helpers/charges_helper.rb
module ChargesHelper
end

eventbrite-devise/app/helpers/events_helper.rb
module EventsHelper
end

eventbrite-devise/app/helpers/home_helper.rb
module HomeHelper
end

eventbrite-devise/app/views/charges/create.html.erb
<h2>Merci, paiement de <strong>$5.00</strong>validé ! </h2>

eventbrite-devise/app/views/charges/new.html.erb
<%= form_tag charges_path do %>
    <article>
      <% if flash[:error].present? %>
        <div id="error_explanation">
          <p><%= flash[:error] %></p>
        </div>
      <% end %>
      <label class="amount">
        <span>Montant: 5.00€</span>
      </label>
    </article>
  
    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button" 
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-description="Paiement"
            data-amount="500"
            data-currency='eur'
            data-locale="auto"></script>
  <% end %>

eventbrite-devise/app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %> <br>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %> <br>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :date %> <br>
    <%= form.datetime_select :date %>
  </div>

  <div class="field">
    <%= form.label :location %> <br>
    <%= form.text_field :location %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

eventbrite-devise/app/views/events/edit.html.erb
<div class="container">
    <h1>Modification de l&rsquo;événement</h1>

    <%= render 'form', event: @event %>

    <%= link_to 'Show', @event %> |
    <%= link_to 'Back', events_path %>
</div>

eventbrite-devise/app/views/events/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Events</h1>
  <hr>

  <table>
    <thead>
      <tr>
        <th>Evenement</th>
        <th>Description</th>
        <th>Date</th>
        <th>Lieu</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @events.each do |event| %>
        <tr>
          <td><%= event.name %></td>
          <td><%= event.description %></td>
          <td><%= event.date %></td>
          <td><%= event.location %></td>

          
          
          <td><a href= <%= "/events/#{event.id}"%>><button type="button" class="btn btn-success"> Voir</button> &nbsp &nbsp <br><br></td> &nbsp &nbsp
          <td><a href= <%= "/events/#{event.id}/edit"%>><button type="button" class="btn btn-warning"> Modifier</button> &nbsp &nbsp <br><br></td> &nbsp &nbsp
          <td><button type="button" class="btn btn-danger btn-small"><%= link_to 'Supprimer', event, method: :delete, data: { confirm: 'Hey, t&rsquo;es sur de toi ?' } %></button> &nbsp &nbsp <br><br></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <hr>
  &nbsp <br>
  <br>
  <a href= <%=new_event_path%>>
  <button type="button" class="btn btn-info"> Nouvel événement</button></a>
  


  
  </div>

eventbrite-devise/app/views/events/new.html.erb
<div class="container">
    <h1>Nouvel événement</h1>
    <hr>
    <%= render 'form', event: @event %>
    
    <%= link_to 'Retour', events_path %>
</div>

eventbrite-devise/app/views/events/show.html.erb
<hr>
<div class='container'>
  <form_action = 'charges_path method' ='POST'>
    <article>
      <% if flash[:error].present? %>
         <div id="error_explanation">
          <p><%= flash[:error] %></p>
</div>
      <% end %>
      <label class="amount">
        <span>Montant: 5.00€</span>
      </label>
    </article>

    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button" 
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-description="Paiement"
            data-amount="500"
            data-currency='eur'
            data-locale="auto">
    </script>
  </form>
</div>

<hr>
<div class='container'>

  <p id="notice"><%= notice %></p>
  
  <p>
    <strong>Name:</strong>
    <%= @event.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @event.description %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= @event.date %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= @event.location %>
  </p>

  <%= link_to 'Edit', edit_event_path(@event) %> |
  <%= link_to 'Back', events_path %>
</div>
<hr>

eventbrite-devise/app/views/home/index.html.erb
<div class="container">
    <% if user_signed_in? && current_user.email == "broussolle.paul@gmail.com" %>
       <h1> Bienvenue Paulo 🐽 </h1>
    <% elsif user_signed_in? %>
        <h1>Bienvenue  <%= current_user.email %> </h1> 
        <hr>
        <a href= <%=new_event_path%>>
        <button type="button" class="btn btn-info"> Nouvel événement</button></a>
    <% else %>
        <h1>Bienvenue l&rsquo;ami 🐽 </h1>
        <hr>
        <a href= <%=new_user_registration_path%>><button type="button" class="btn btn-success"> <span class="glyphicon glyphicon-user"></span>&nbsp Sign Up</button></a> &nbsp &nbsp
        <a href= <%=new_user_session_path%>><button type="button" class="btn btn-primary"> <span class="glyphicon glyphicon-log-in"></span> &nbsp Login</button> </a>
    <% end %>
</div>

eventbrite-devise/app/views/home/private.html.erb
<h1>Home#private</h1>
<p>Find me in app/views/home/private.html.erb</p>

eventbrite-devise/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href=<% root_path%>>Eventbrite</a>
    </div>

    <ul class="nav navbar-nav">
      <li><a href=<% root_path%>>Accueil</a></li>
        <li><a href= <%=events_path%>>Nos évènements</a></li>
        <% if user_signed_in? %>
            <li><a href= <%=new_event_path%> >Nouvel événement</a></li>
        <% end %>
    </ul>

    <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <li><a href= <%=user_session_path%>><span class="glyphicon glyphicon-user"></span> <%= current_user.email %></a></li>
            <li><%= link_to  destroy_user_session_path, method: :delete do %> <span class="glyphicon glyphicon-log-in"></span> Se déconnecter <%end%></li>
        <% else %>
            <li><a href= <%=new_user_registration_path%>><span class="glyphicon glyphicon-user"></span> S&rsquo;inscrire</a></li>
            <li><a href= <%=new_user_session_path%>><span class="glyphicon glyphicon-log-in"></span> Se connecter</a></li>
        <% end %>
    </ul>
  </div>
</nav>
  

eventbrite-devise/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventbriteDevise</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    </head>

  <body>
       <%= render 'layouts/navbar' %>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>